dist: xenial
sudo: enabled

addons:
  apt:
    packages:
    - gnat
    - gprbuild

script:
  - mkdir obj
  - mkdir obj/debug
  - mkdir obj/release
  - gprbuild -d -P constraintengine -Xmode=debug
  - gprbuild -d -P constraintengine -Xmode=release
