dist: xenial
sudo: enabled

addons:
  apt:
    packages:
    - gnat
    - gprbuild

before_script:
  - git clone https://github.com/alire-project/libaunit.git AUnit && cd AUnit
  - cat Makefile | sed -e 's/lib\/gnat\///g' > Makefile
  - make install

script:
  - mkdir obj
  - mkdir obj/debug
  - mkdir obj/release
  - gprbuild -d -P constraintengine -Xmode=debug
  - gprbuild -d -P constraintengine -Xmode=release
